name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest langchain langchain_community langchain_huggingface langchain_chroma unstructured huggingface_hub chromadb sentence-transformers llama-cpp-python pypdf

    - name: Run flake8
      run: |
        flake8 . --max-line-length=88 --extend-ignore=E203,E501

    - name: Run tests
      run: |
        pytest